### ISSUE TITLE
targetTags not optional

### ISSUE THREAD

**Issue by paddatrapper** [giantswarm/silence-operator#251]
The README documents targetTags as optional, however leaving the targetTags out results in the following error:

```
error: error validating "temp.yaml": error validating data: ValidationError(Silence.spec): missing required field "targetTags" in io.giantswarm.monitoring.v1alpha1.Silence.spec; if you choose to ignore these errors, turn validation off wit
h --validate=false
```

CR:

```yaml
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: test-silence1
spec:
  matchers:
  - name: cluster
    value: test
    isRegex: false
```
